### ISSUE TITLE
Save xlsx file to []bytes or io.Writer

### ISSUE THREAD

**Issue by LucienLS** [plandem/xlsx2go#28]
Hi, man, this xlsx libary is very useful for me to read big excel files, but there have a pity the file can only save by fileName, why not provide a method to save as []byte or to io.Writer.

**Comment by plandem** [comment]
Hi. Yep, why not. it should not be difficult at extend `SaveAs` method

**Comment by plandem** [comment]
I added io.Writer support. Try to use SaveAs
